[2024-09-20T15:13:51.999+0000] {processor.py:161} INFO - Started process (PID=88) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_sla_dag.py
[2024-09-20T15:13:52.005+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2024-09-20T15:13:52.018+0000] {logging_mixin.py:188} INFO - [2024-09-20T15:13:52.015+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_sla_dag.py
[2024-09-20T15:13:52.345+0000] {processor.py:840} INFO - DAG(s) 'example_sla_dag' retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_sla_dag.py
[2024-09-20T15:13:52.736+0000] {logging_mixin.py:188} INFO - [2024-09-20T15:13:52.732+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-09-20T15:13:52.909+0000] {logging_mixin.py:188} INFO - [2024-09-20T15:13:52.909+0000] {dag.py:3947} INFO - Setting next_dagrun for example_sla_dag to 2024-09-20 15:10:00+00:00, run_after=2024-09-20 15:12:00+00:00
[2024-09-20T15:13:53.088+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_sla_dag.py took 1.139 seconds
[2024-09-20T15:13:57.371+0000] {processor.py:161} INFO - Started process (PID=100) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_sla_dag.py
[2024-09-20T15:13:57.466+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2024-09-20T15:13:57.472+0000] {logging_mixin.py:188} INFO - [2024-09-20T15:13:57.471+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_sla_dag.py
[2024-09-20T15:13:57.485+0000] {processor.py:840} INFO - DAG(s) 'example_sla_dag' retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_sla_dag.py
[2024-09-20T15:13:57.515+0000] {logging_mixin.py:188} INFO - [2024-09-20T15:13:57.514+0000] {taskinstance.py:2907} ERROR - {'DAG Id': 'example_sla_dag', 'Task Id': 'sleep_20', 'Run Id': 'scheduled__2024-08-28T19:00:00+00:00', 'Hostname': '1d2bd9c1668e', 'External Executor Id': '7e94638c-62c4-43b7-8524-d9355e0142f7'}
[2024-09-20T15:13:57.550+0000] {logging_mixin.py:188} INFO - [2024-09-20T15:13:57.550+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=example_sla_dag, task_id=sleep_20, run_id=scheduled__2024-08-28T19:00:00+00:00, execution_date=20240828T190000, start_date=20240828T192731, end_date=20240920T151357
[2024-09-20T15:13:57.585+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-09-20T15:13:57.585+0000] {logging_mixin.py:188} INFO - [2024-09-20T15:13:57.585+0000] {configuration.py:1053} WARNING - section/key [smtp/smtp_user] not found in config
[2024-09-20T15:13:57.586+0000] {logging_mixin.py:188} INFO - [2024-09-20T15:13:57.586+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-09-20T15:13:57.592+0000] {logging_mixin.py:188} INFO - [2024-09-20T15:13:57.591+0000] {configuration.py:1053} WARNING - section/key [smtp/smtp_user] not found in config
[2024-09-20T15:13:57.592+0000] {logging_mixin.py:188} INFO - [2024-09-20T15:13:57.592+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-09-20T15:13:57.598+0000] {logging_mixin.py:188} INFO - [2024-09-20T15:13:57.593+0000] {taskinstance.py:879} ERROR - Failed to send email to: email@example.com
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1063, in _email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 853, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 838, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 877, in _handle_failure
    task_instance.email_alert(error, failure_context["task"])
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3163, in email_alert
    _email_alert(task_instance=self, exception=exception, task=task)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1065, in _email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 853, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 838, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-09-20T15:13:57.617+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: example_sla_dag.sleep_20 scheduled__2024-08-28T19:00:00+00:00 [failed]> in state failed
[2024-09-20T15:13:57.621+0000] {logging_mixin.py:188} INFO - [2024-09-20T15:13:57.621+0000] {taskinstance.py:2907} ERROR - {'DAG Id': 'example_sla_dag', 'Task Id': 'sleep_20', 'Run Id': 'scheduled__2024-08-28T18:58:00+00:00', 'Hostname': '1d2bd9c1668e', 'External Executor Id': '382e35fb-23d6-472a-9195-a828e8ee68b8'}
[2024-09-20T15:13:57.640+0000] {logging_mixin.py:188} INFO - [2024-09-20T15:13:57.640+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=example_sla_dag, task_id=sleep_20, run_id=scheduled__2024-08-28T18:58:00+00:00, execution_date=20240828T185800, start_date=20240828T192724, end_date=20240920T151357
[2024-09-20T15:13:57.794+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-09-20T15:13:57.795+0000] {logging_mixin.py:188} INFO - [2024-09-20T15:13:57.795+0000] {configuration.py:1053} WARNING - section/key [smtp/smtp_user] not found in config
[2024-09-20T15:13:57.796+0000] {logging_mixin.py:188} INFO - [2024-09-20T15:13:57.795+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-09-20T15:13:57.801+0000] {logging_mixin.py:188} INFO - [2024-09-20T15:13:57.801+0000] {configuration.py:1053} WARNING - section/key [smtp/smtp_user] not found in config
[2024-09-20T15:13:57.802+0000] {logging_mixin.py:188} INFO - [2024-09-20T15:13:57.802+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-09-20T15:13:57.807+0000] {logging_mixin.py:188} INFO - [2024-09-20T15:13:57.803+0000] {taskinstance.py:879} ERROR - Failed to send email to: email@example.com
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1063, in _email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 853, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 838, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 877, in _handle_failure
    task_instance.email_alert(error, failure_context["task"])
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3163, in email_alert
    _email_alert(task_instance=self, exception=exception, task=task)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1065, in _email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 853, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 838, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-09-20T15:13:57.815+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: example_sla_dag.sleep_20 scheduled__2024-08-28T18:58:00+00:00 [failed]> in state failed
[2024-09-20T15:13:57.938+0000] {logging_mixin.py:188} INFO - [2024-09-20T15:13:57.937+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-09-20T15:13:57.994+0000] {logging_mixin.py:188} INFO - [2024-09-20T15:13:57.994+0000] {dag.py:3947} INFO - Setting next_dagrun for example_sla_dag to 2024-09-20 15:10:00+00:00, run_after=2024-09-20 15:12:00+00:00
[2024-09-20T15:13:58.246+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_sla_dag.py took 0.881 seconds
