[2024-09-25T09:41:58.263+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-25T09:41:58.299+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NY_TAXI.download_data scheduled__2021-05-01T00:00:00+00:00 [queued]>
[2024-09-25T09:41:58.318+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NY_TAXI.download_data scheduled__2021-05-01T00:00:00+00:00 [queued]>
[2024-09-25T09:41:58.319+0000] {taskinstance.py:2865} INFO - Starting attempt 16 of 16
[2024-09-25T09:41:58.365+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): download_data> on 2021-05-01 00:00:00+00:00
[2024-09-25T09:41:58.383+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'NY_TAXI', 'download_data', 'scheduled__2021-05-01T00:00:00+00:00', '--job-id', '461', '--raw', '--subdir', 'DAGS_FOLDER/download.py', '--cfg-path', '/tmp/tmplt_pa92j']
[2024-09-25T09:41:58.386+0000] {standard_task_runner.py:105} INFO - Job 461: Subtask download_data
[2024-09-25T09:41:58.387+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1267) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-25T09:41:58.387+0000] {standard_task_runner.py:72} INFO - Started process 1283 to run task
[2024-09-25T09:41:58.499+0000] {task_command.py:467} INFO - Running <TaskInstance: NY_TAXI.download_data scheduled__2021-05-01T00:00:00+00:00 [running]> on host e7ca35b1115e
[2024-09-25T09:41:58.764+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='NY_TAXI' AIRFLOW_CTX_TASK_ID='download_data' AIRFLOW_CTX_EXECUTION_DATE='2021-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='16' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-05-01T00:00:00+00:00'
[2024-09-25T09:41:58.770+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-25T09:41:58.912+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-25T09:41:58.914+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'curl -sSL https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-05.csv.gz > /opt/***/output_2021-05.csv.gz']
[2024-09-25T09:41:59.042+0000] {subprocess.py:86} INFO - Output:
[2024-09-25T09:42:47.164+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-09-25T09:42:47.166+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-25T09:42:47.355+0000] {process_utils.py:132} INFO - Sending 15 to group 1283. PIDs of all processes in the group: [1285, 1286, 1283]
[2024-09-25T09:42:47.356+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1283
[2024-09-25T09:42:47.357+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-25T09:42:47.358+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-09-25T09:42:47.381+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 240, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-09-25T09:42:47.894+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=NY_TAXI, task_id=download_data, run_id=scheduled__2021-05-01T00:00:00+00:00, execution_date=20210501T000000, start_date=20240925T094158, end_date=20240925T094247
[2024-09-25T09:42:48.066+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1286, status='terminated', started='09:41:58') (1286) terminated with exit code None
[2024-09-25T09:42:48.909+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-25T09:42:48.977+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1285, status='terminated', started='09:41:58') (1285) terminated with exit code None
[2024-09-25T09:42:48.978+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1283, status='terminated', exitcode=2, started='09:41:57') (1283) terminated with exit code 2
